version: '3.9'

services:
  postgres-drones:
    image: postgres:15
    container_name: postgres-drones
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  drones-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drones-api
    restart: on-failure
    depends_on:
      - postgres-drones
    ports:
      - "8080:8080"   # HTTP + Swagger
      - "50051:50051" # gRPC
    env_file:
      - .env

volumes:
  postgres-data:
