// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: drone-client/api/v1/drones/drones.proto

package drones

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Drones_StartDroneMission_FullMethodName = "/drone_client.api.v1.drones.Drones/StartDroneMission"
)

// DronesClient is the client API for Drones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DronesClient interface {
	StartDroneMission(ctx context.Context, in *StartDroneMission_Request, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dronesClient struct {
	cc grpc.ClientConnInterface
}

func NewDronesClient(cc grpc.ClientConnInterface) DronesClient {
	return &dronesClient{cc}
}

func (c *dronesClient) StartDroneMission(ctx context.Context, in *StartDroneMission_Request, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drones_StartDroneMission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DronesServer is the server API for Drones service.
// All implementations must embed UnimplementedDronesServer
// for forward compatibility.
type DronesServer interface {
	StartDroneMission(context.Context, *StartDroneMission_Request) (*emptypb.Empty, error)
	mustEmbedUnimplementedDronesServer()
}

// UnimplementedDronesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDronesServer struct{}

func (UnimplementedDronesServer) StartDroneMission(context.Context, *StartDroneMission_Request) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDroneMission not implemented")
}
func (UnimplementedDronesServer) mustEmbedUnimplementedDronesServer() {}
func (UnimplementedDronesServer) testEmbeddedByValue()                {}

// UnsafeDronesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DronesServer will
// result in compilation errors.
type UnsafeDronesServer interface {
	mustEmbedUnimplementedDronesServer()
}

func RegisterDronesServer(s grpc.ServiceRegistrar, srv DronesServer) {
	// If the following call pancis, it indicates UnimplementedDronesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Drones_ServiceDesc, srv)
}

func _Drones_StartDroneMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDroneMission_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DronesServer).StartDroneMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drones_StartDroneMission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DronesServer).StartDroneMission(ctx, req.(*StartDroneMission_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Drones_ServiceDesc is the grpc.ServiceDesc for Drones service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Drones_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone_client.api.v1.drones.Drones",
	HandlerType: (*DronesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDroneMission",
			Handler:    _Drones_StartDroneMission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drone-client/api/v1/drones/drones.proto",
}
