// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: api/v1/drones/drones.proto

package drones

import (
	model "github.com/VeneLooool/drones-api/internal/pb/api/v1/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDrone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDrone) Reset() {
	*x = CreateDrone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDrone) ProtoMessage() {}

func (x *CreateDrone) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDrone.ProtoReflect.Descriptor instead.
func (*CreateDrone) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{0}
}

type UpdateDrone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDrone) Reset() {
	*x = UpdateDrone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrone) ProtoMessage() {}

func (x *UpdateDrone) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrone.ProtoReflect.Descriptor instead.
func (*UpdateDrone) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{1}
}

type GetDroneByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDroneByID) Reset() {
	*x = GetDroneByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDroneByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDroneByID) ProtoMessage() {}

func (x *GetDroneByID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDroneByID.ProtoReflect.Descriptor instead.
func (*GetDroneByID) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{2}
}

type DeleteDrone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDrone) Reset() {
	*x = DeleteDrone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDrone) ProtoMessage() {}

func (x *DeleteDrone) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDrone.ProtoReflect.Descriptor instead.
func (*DeleteDrone) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{3}
}

type CreateDrone_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateDrone_Request) Reset() {
	*x = CreateDrone_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDrone_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDrone_Request) ProtoMessage() {}

func (x *CreateDrone_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDrone_Request.ProtoReflect.Descriptor instead.
func (*CreateDrone_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateDrone_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDrone_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drone *model.Drone `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone,omitempty"`
}

func (x *CreateDrone_Response) Reset() {
	*x = CreateDrone_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDrone_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDrone_Response) ProtoMessage() {}

func (x *CreateDrone_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDrone_Response.ProtoReflect.Descriptor instead.
func (*CreateDrone_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateDrone_Response) GetDrone() *model.Drone {
	if x != nil {
		return x.Drone
	}
	return nil
}

type UpdateDrone_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateDrone_Request) Reset() {
	*x = UpdateDrone_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDrone_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrone_Request) ProtoMessage() {}

func (x *UpdateDrone_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrone_Request.ProtoReflect.Descriptor instead.
func (*UpdateDrone_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UpdateDrone_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDrone_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDrone_Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateDrone_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drone *model.Drone `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone,omitempty"`
}

func (x *UpdateDrone_Response) Reset() {
	*x = UpdateDrone_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDrone_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrone_Response) ProtoMessage() {}

func (x *UpdateDrone_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrone_Response.ProtoReflect.Descriptor instead.
func (*UpdateDrone_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{1, 1}
}

func (x *UpdateDrone_Response) GetDrone() *model.Drone {
	if x != nil {
		return x.Drone
	}
	return nil
}

type GetDroneByID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDroneByID_Request) Reset() {
	*x = GetDroneByID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDroneByID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDroneByID_Request) ProtoMessage() {}

func (x *GetDroneByID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDroneByID_Request.ProtoReflect.Descriptor instead.
func (*GetDroneByID_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetDroneByID_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDroneByID_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drone *model.Drone `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone,omitempty"`
}

func (x *GetDroneByID_Response) Reset() {
	*x = GetDroneByID_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDroneByID_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDroneByID_Response) ProtoMessage() {}

func (x *GetDroneByID_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDroneByID_Response.ProtoReflect.Descriptor instead.
func (*GetDroneByID_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetDroneByID_Response) GetDrone() *model.Drone {
	if x != nil {
		return x.Drone
	}
	return nil
}

type DeleteDrone_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDrone_Request) Reset() {
	*x = DeleteDrone_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_drones_drones_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDrone_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDrone_Request) ProtoMessage() {}

func (x *DeleteDrone_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_drones_drones_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDrone_Request.ProtoReflect.Descriptor instead.
func (*DeleteDrone_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_drones_drones_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DeleteDrone_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_v1_drones_drones_proto protoreflect.FileDescriptor

var file_api_v1_drones_drones_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2f,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x64, 0x72,
	0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x1a, 0x1d, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x44, 0x72, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x22, 0x96, 0x01, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x1a, 0x45, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x05, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x52, 0x05,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x22, 0x6b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e,
	0x65, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x72,
	0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x64, 0x72, 0x6f,
	0x6e, 0x65, 0x22, 0x28, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e,
	0x65, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0x93, 0x04, 0x0a,
	0x06, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x83, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x2d, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x3a, 0x01,
	0x2a, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x88, 0x01,
	0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x2d, 0x2e,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x64,
	0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72,
	0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x14, 0x3a, 0x01, 0x2a, 0x1a, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x72, 0x6f,
	0x6e, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x88, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x44, 0x72, 0x6f, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x2e, 0x2e, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x72,
	0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x42, 0x79, 0x49,
	0x44, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x72,
	0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x42, 0x79, 0x49,
	0x44, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x6d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x6f,
	0x6e, 0x65, 0x12, 0x2d, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x11, 0x2a, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x56, 0x65, 0x6e, 0x65, 0x4c, 0x6f, 0x6f, 0x6f, 0x6f, 0x6c, 0x2f, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x3b, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_drones_drones_proto_rawDescOnce sync.Once
	file_api_v1_drones_drones_proto_rawDescData = file_api_v1_drones_drones_proto_rawDesc
)

func file_api_v1_drones_drones_proto_rawDescGZIP() []byte {
	file_api_v1_drones_drones_proto_rawDescOnce.Do(func() {
		file_api_v1_drones_drones_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_drones_drones_proto_rawDescData)
	})
	return file_api_v1_drones_drones_proto_rawDescData
}

var file_api_v1_drones_drones_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_drones_drones_proto_goTypes = []any{
	(*CreateDrone)(nil),           // 0: drones_api.api.v1.drones.CreateDrone
	(*UpdateDrone)(nil),           // 1: drones_api.api.v1.drones.UpdateDrone
	(*GetDroneByID)(nil),          // 2: drones_api.api.v1.drones.GetDroneByID
	(*DeleteDrone)(nil),           // 3: drones_api.api.v1.drones.DeleteDrone
	(*CreateDrone_Request)(nil),   // 4: drones_api.api.v1.drones.CreateDrone.Request
	(*CreateDrone_Response)(nil),  // 5: drones_api.api.v1.drones.CreateDrone.Response
	(*UpdateDrone_Request)(nil),   // 6: drones_api.api.v1.drones.UpdateDrone.Request
	(*UpdateDrone_Response)(nil),  // 7: drones_api.api.v1.drones.UpdateDrone.Response
	(*GetDroneByID_Request)(nil),  // 8: drones_api.api.v1.drones.GetDroneByID.Request
	(*GetDroneByID_Response)(nil), // 9: drones_api.api.v1.drones.GetDroneByID.Response
	(*DeleteDrone_Request)(nil),   // 10: drones_api.api.v1.drones.DeleteDrone.Request
	(*model.Drone)(nil),           // 11: drones_api.api.v1.model.Drone
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_api_v1_drones_drones_proto_depIdxs = []int32{
	11, // 0: drones_api.api.v1.drones.CreateDrone.Response.drone:type_name -> drones_api.api.v1.model.Drone
	11, // 1: drones_api.api.v1.drones.UpdateDrone.Response.drone:type_name -> drones_api.api.v1.model.Drone
	11, // 2: drones_api.api.v1.drones.GetDroneByID.Response.drone:type_name -> drones_api.api.v1.model.Drone
	4,  // 3: drones_api.api.v1.drones.Drones.CreateDrone:input_type -> drones_api.api.v1.drones.CreateDrone.Request
	6,  // 4: drones_api.api.v1.drones.Drones.UpdateDrone:input_type -> drones_api.api.v1.drones.UpdateDrone.Request
	8,  // 5: drones_api.api.v1.drones.Drones.GetDroneByID:input_type -> drones_api.api.v1.drones.GetDroneByID.Request
	10, // 6: drones_api.api.v1.drones.Drones.DeleteDrone:input_type -> drones_api.api.v1.drones.DeleteDrone.Request
	5,  // 7: drones_api.api.v1.drones.Drones.CreateDrone:output_type -> drones_api.api.v1.drones.CreateDrone.Response
	7,  // 8: drones_api.api.v1.drones.Drones.UpdateDrone:output_type -> drones_api.api.v1.drones.UpdateDrone.Response
	9,  // 9: drones_api.api.v1.drones.Drones.GetDroneByID:output_type -> drones_api.api.v1.drones.GetDroneByID.Response
	12, // 10: drones_api.api.v1.drones.Drones.DeleteDrone:output_type -> google.protobuf.Empty
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_drones_drones_proto_init() }
func file_api_v1_drones_drones_proto_init() {
	if File_api_v1_drones_drones_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_drones_drones_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDrone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDrone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetDroneByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDrone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDrone_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDrone_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDrone_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDrone_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetDroneByID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetDroneByID_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_drones_drones_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDrone_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_drones_drones_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_drones_drones_proto_goTypes,
		DependencyIndexes: file_api_v1_drones_drones_proto_depIdxs,
		MessageInfos:      file_api_v1_drones_drones_proto_msgTypes,
	}.Build()
	File_api_v1_drones_drones_proto = out.File
	file_api_v1_drones_drones_proto_rawDesc = nil
	file_api_v1_drones_drones_proto_goTypes = nil
	file_api_v1_drones_drones_proto_depIdxs = nil
}
